# Se definen variales a ser utilizadas en el Makefile
JFLAGS = -g
JC = javac
JM = java
MAIN = Stage1
# FILE = ruta de algun archivo


# Se definen las clases
CLASSES = \
Cloud.java \
Lamp.java \
Stage1.java

# Que accion realizar por defecto
default: compile

# Se define la accion
compile:
	$(JC) $(JFLAGS) $(CLASSES)
